SELECT TOP (1000) [COUNTRY]
      ,[PROVINCE]
      ,[CITY]
      ,[PROPERTY_PRICE]
      ,[BEDROOMS]
      ,[BATHROOM]
      ,[PARKING]
      ,[FLOORSIZE]
      ,[MONTHLY_REPAYMENT]
      ,[TOTAL_ONCE_OFF_COST]
      ,[MIN_GROSS_MONTHLY_INCOME]
  FROM [property24].[dbo].[property_details]
